spring:
  profiles:
    active: default
  datasource:
    url: jdbc:h2:mem:order;MODE=MYSQL
    driverClassName: org.h2.Driver
    username: root
    password: password
kafka:
  bootstrapAddress: localhost:9092
  topics:
    name: order